#
# CUSTOM PARAMETER FILE TO GIVE CONES PARAMETERS ACCORDING TO DIR_NAME
#

parameters:
  deus_files:
      snapshot_cubes:
        path: ""
        dir_pattern: "/cube_([0-9]{5})/"
        geometry_type: snapshot
        file_pattern: "/fof_boxlen<boxlen>_n<npart>_<cosmo>_cube_([0-9]{5})/"
        file_type: cube
        file_format: fof
      snapshot_masst:
        path: "post/fof/"
        dir_pattern: "/output_([0-9]{5})/"
        geometry_type: snapshot
        file_pattern: "/fof_boxlen<boxlen>_n<npart>_<cosmo>_masst_([0-9]{5})/"
        file_format: fof
        file_type: masst
      snapshot_strct:
        path: "post/fof/"
        dir_pattern: "/output_([0-9]{5})/"
        geometry_type: snapshot
        file_pattern: "/fof_boxlen<boxlen>_n<npart>_<cosmo>_strct_([0-9]{5})/"
        file_format: fof
        file_type: strct
      cone_hdf5_strct:
        path: "post/fof/"
        dir_pattern: "/cone_(.*)/"
        geometry_type: cone
        file_pattern: "/boxlen<boxlen>_n<npart>_<cosmo>_fullsky_halo_([0-9]{5})\.h5/"
        file_format: hdf5
        file_type: strct
      cone_hdf5_masst:
        path: "post/fof/"
        dir_pattern: "/cone_(.*)/"
        geometry_type: cone
        file_pattern: "/boxlen<boxlen>_n<npart>_<cosmo>_fullsky_halomass.h5/"
        file_format: hdf5
        file_type: masst
#      cone_fur_cubes:
#        path: "post/slicer_ncoarse"
#        dir_pattern: "/output_(.*)/"
#        geometry_type: cone
#        file_pattern: "/fof_cone<boxlen>_n<npart>_<cosmo>_dosamplecone_masst_([0-9]{5})/"
#        file_format: fof
#        file_type: masst


