#
# CUSTOM PARAMETER FILE TO GIVE CONES PARAMETERS ACCORDING TO DIR_NAME
#

parameters:
  deus_files:
      snapshot_cubes:
        path: ""
        dir_pattern: "cube_?????"
        file_pattern: "fof_boxlen<boxlen>_n<npart>_<cosmo>_cube_?????"
        file_format: fof
        file_type: cube
        geometry_type: snapshot
      snapshot_masst:
        path: "post/fof/"
        dir_pattern: "output_?????"
        file_pattern: "fof_boxlen<boxlen>_n<npart>_<cosmo>_masst_?????"
        file_format: fof
        file_type: masst
        geometry_type: snapshot
      snapshot_strct:
        path: "post/fof/"
        dir_pattern: "output_?????"
        file_pattern: "fof_boxlen<boxlen>_n<npart>_<cosmo>_strct_?????"
        file_format: fof
        file_type: strct
        geometry_type: snapshot
      cone_fur_cubes:
        path: "post/slicer_ncoarse"
        dir_pattern: "output_cone_?"
        file_pattern: "fof_cone<boxlen>_n<npart>_<cosmo>_dosamplecone_masst_?????"
        file_format: fof
        file_type: masst
        geometry_type: cone

